### ISSUE TITLE
Please create new embedded episode on website.

### ISSUE THREAD

**Issue by KyleBrouseEclipse** [EclipseFdn/entrepreneurialopensource.org#11]
Hi, here is the embed code for the new episode of the podcast to be added to the website. Please do not publish this change until the morning of Wednesday June 23rd, when the episode is released. Thank you! 

<div id="buzzsprout-player-8681016"></div>
<script src="https://www.buzzsprout.com/1740291/8681016-webtide-episode.js?container_id=buzzsprout-player-8681016&player=small" type="text/javascript" charset="utf-8"></script>

**Comment by linkfang** [comment]
The episode was added automatically when it's live!
https://entrepreneurialopensource.org/
