### ISSUE TITLE
Listen and share icons missing

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/entrepreneurialopensource.org#3]
Icons in the orange bar for "Listen" and "Share" are not loading:

![image](https://user-images.githubusercontent.com/61751191/117357629-2e8eee80-ae83-11eb-9d77-cd3347facb73.png)

**Comment by chrisguindon** [comment]
I notice the same thing as well!

@linkfang already posted a fix and that problem should be gone any minute now.
