### ISSUE TITLE
Change default text for Twitter share from entrepreneurialopensource.org/

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/entrepreneurialopensource.org#7]
Can we change the text that automatically comes up when pressing the Twitter share button on the Entrepreneurial Open Source website?

Right now the default tweet reads "Be a guest of Entrepreneurial Open Source Podcast." We'd like to change it to "Listen to the Entrepreneurial Open Source Podcast" 

Screenshot attached for reference
<img width="607" alt="Screen Shot 2021-05-28 at 3 28 23 PM" src="https://user-images.githubusercontent.com/69642121/120205954-958c9280-c1f8-11eb-9ce4-13a692eb6b62.png">

**Comment by linkfang** [comment]
Hi @jph152 , the change is now live:
https://entrepreneurialopensource.org/
