### ISSUE TITLE
Please update the website with the upcoming episode embedded player

### ISSUE THREAD

**Issue by KyleBrouseEclipse** [EclipseFdn/entrepreneurialopensource.org#9]
New episode embedded player. Can you put it above the current player that is already listed. Here is the embed code 

<div id="buzzsprout-player-8624400"></div>
<script src="https://www.buzzsprout.com/1740291/8624400-entrepreneurial-open-source-podcast-frank-gielissen-glenn-ergeerts-aloxy.js?container_id=buzzsprout-player-8624400&player=small" type="text/javascript" charset="utf-8"></script>

Thank you.

**Comment by linkfang** [comment]
Hi @KyleBrouseEclipse , please review the change here:
https://deploy-preview-10--eclipsefdn-entrepreneurialopensource.netlify.app/?utm_source=github&utm_campaign=bot_dp

**Comment by linkfang** [comment]
Hi @KyleBrouseEclipse , looks like the episode will be updated automatically once it is live.
https://entrepreneurialopensource.org/

So, I will just close this issue.
Thanks
